version: "3"
services:
  # Web
  web:
    image: nginx
    volumes:
      - ".:/app"
      - "./docker_dev/nginx/site.conf:/etc/nginx/conf.d/default.conf"
      - "./docker_dev/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    depends_on:
      - php
    ports:
      - "8000:80"
  php:
    build:
      context: .
      dockerfile: docker_dev/Dockerfile
    volumes:
      - ".:/app"
      - "./docker_dev/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"